apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: leaderelection-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leaderelection-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leaderelection-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leaderelection-role
subjects:
  - kind: ServiceAccount
    name: leaderelection-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sleader
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sleader
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8sleader
    spec:
      automountServiceAccountToken: true
      serviceAccount: leaderelection-sa
      containers:
      - image: arieswangdocker/k8sleader:latest  
        imagePullPolicy: Always
        name: k8sleader
        command: ["./k8sleader_latest"]
        args: ["-lease-lock-name=aaa","-lease-lock-namespace=default"]
        ports:
        - containerPort: 8080
          protocol: TCP